import numpy as np

COST_FUNCTIONS_DIRNAME = 'cost_functions'
COST_FUNCTION_F_FILENAME = 'f.npy'
COST_FUNCTION_DF_FILENAME = 'df.npy'
COST_FUNCTION_F_NORMALIZED_FILENAME = 'f_normalized.npy'
COST_FUNCTION_CORRELATION_PARAMETER_FILENAME = 'cp.npy'

COST_FUNCTION_F_OPTION_FILENAME = 'f_options.npy'
COST_FUNCTION_DF_OPTION_FILENAME = 'df_options.npy'
# COST_FUNCTION_NODES_SETUP_SPINUP = ('f_ocean2', 5, 16)
# COST_FUNCTION_NODES_SETUP_DERIVATIVE = ('foexpress', 2, 16)
# COST_FUNCTION_NODES_SETUP_TRAJECTORY = ('foexpress', 1, 16)
COST_FUNCTION_NODES_SETUP_SPINUP = ('f_ocean2', 6, 16)
# COST_FUNCTION_NODES_SETUP_DERIVATIVE = ('f_ocean2', 6, 16)
COST_FUNCTION_NODES_SETUP_DERIVATIVE = ('f_ocean', 12, 8)
# COST_FUNCTION_NODES_SETUP_TRAJECTORY = ('westmere', 1, 1)
COST_FUNCTION_NODES_SETUP_TRAJECTORY = ('f_ocean', 1, 8)


PARAMETER_BOUNDS = np.array([[0.05, 0.95], [0.5, 10], [0.05, 0.95], [0.005, 10], [10, 50], [0.001, 0.2], [0.7 , 1.3]]).T
CONCENTRATION_MIN_VALUE = 0.001
