COST_FUNCTIONS_DIRNAME = 'cost_functions'
COST_FUNCTION_F_FILENAME = 'f.npy'
COST_FUNCTION_DF_FILENAME = 'df.npy'
COST_FUNCTION_F_NORMALIZED_FILENAME = 'f_normalized.npy'
COST_FUNCTION_CORRELATION_PARAMETER_FILENAME = 'cp.npy'

COST_FUNCTION_F_OPTION_FILENAME = 'f_options.npy'
COST_FUNCTION_DF_OPTION_FILENAME = 'df_options.npy'
COST_FUNCTION_NODES_SETUP_SPINUP = ('f_ocean2', 3, 16)
COST_FUNCTION_NODES_SETUP_DERIVATIVE = ('f_ocean2', 3, 16)
# COST_FUNCTION_NODES_SETUP_DERIVATIVE = ('f_ocean', 7, 8)

