import os.path

import util.io.env

SIMULATION_OUTPUT_DIR_ENV_NAME = 'SIMULATION_OUTPUT_DIR'
SIMULATION_OUTPUT_DIR = util.io.env.load(SIMULATION_OUTPUT_DIR_ENV_NAME)

METOS3D_DIR_ENV_NAME = 'METOS3D_DIR'
METOS3D_DIR = util.io.env.load(METOS3D_DIR_ENV_NAME)
