MATLAB_PARAMETER_FILENAME = 'p.mat'
MATLAB_F_FILENAME = 'f.mat'
MATLAB_DF_FILENAME = 'df.mat'
NODES_MAX_FILENAME = 'max_nodes.txt'

KIND_OF_COST_FUNCTIONS=('WOA_OLS', 'WOA_WLS', 'WOD_OLS', 'WOD_WLS', 'WOD_GLS', 'WOA_LWLS', 'WOD_LWLS', 'OLD_WOD_WLS', 'OLD_WOD_LWLS')