MATLAB_EVAL_YEARS = 3500
MATLAB_EVAL_TOLERANCE = 10**(-3)
MATLAB_EVAL_TIME_STEP_SIZE = 4
MATLAB_EVAL_DEBUG_LEVEL = 100

MATLAB_EVAL_EXCHANGE_DIR = '/work_j2/sunip229/tmp/matlab_python_exchange'
MATLAB_EVAL_PARAMETER_FILE = MATLAB_EVAL_EXCHANGE_DIR + '/p.mat'
MATLAB_EVAL_F_FILE = MATLAB_EVAL_EXCHANGE_DIR + '/f.mat'
MATLAB_EVAL_DF_FILE = MATLAB_EVAL_EXCHANGE_DIR + '/df.mat'

MATLAB_PARAMETER_FILENAME = 'p.mat'
MATLAB_F_FILENAME = 'f.mat'
MATLAB_DF_FILENAME = 'df.mat'
MAX_NODES_FILENAME = 'max_nodes.txt'