# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Fri Apr 19 16:32:51 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(597, 424)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 220, 81, 28))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 20, 361, 193))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBox_2 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.comboBox_3 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBox_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBox_4 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBox_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.comboBox_5 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_5)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.draw_plot)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.set_parameter_set)
        QtCore.QObject.connect(self.comboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.set_tracer_index)
        QtCore.QObject.connect(self.comboBox_3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.set_time_index)
        QtCore.QObject.connect(self.comboBox_4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.set_depth_index)
        QtCore.QObject.connect(self.comboBox_5, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.set_sensitivity_index)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "draw plots", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "parameter set: ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "tracer: ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("Dialog", "DOP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("Dialog", "PO4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "time: ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("Dialog", "annual", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("Dialog", "January", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("Dialog", "February", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(3, QtGui.QApplication.translate("Dialog", "March", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(4, QtGui.QApplication.translate("Dialog", "April", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(5, QtGui.QApplication.translate("Dialog", "May", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(6, QtGui.QApplication.translate("Dialog", "June", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(7, QtGui.QApplication.translate("Dialog", "July", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(8, QtGui.QApplication.translate("Dialog", "August", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(9, QtGui.QApplication.translate("Dialog", "September", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(10, QtGui.QApplication.translate("Dialog", "October", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(11, QtGui.QApplication.translate("Dialog", "November", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(12, QtGui.QApplication.translate("Dialog", "December", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "depth: ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(0, QtGui.QApplication.translate("Dialog", "0m - 50m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(1, QtGui.QApplication.translate("Dialog", "50m - 120m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(2, QtGui.QApplication.translate("Dialog", "120m - 220m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(3, QtGui.QApplication.translate("Dialog", "220m - 360m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(4, QtGui.QApplication.translate("Dialog", "360m - 550m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(5, QtGui.QApplication.translate("Dialog", "550m - 790m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(6, QtGui.QApplication.translate("Dialog", "790m - 1080m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(7, QtGui.QApplication.translate("Dialog", "1080m - 1420m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(8, QtGui.QApplication.translate("Dialog", "1420m - 1810m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(9, QtGui.QApplication.translate("Dialog", "1810m - 2250m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(10, QtGui.QApplication.translate("Dialog", "2250m - 2740m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(11, QtGui.QApplication.translate("Dialog", "2740m - 3280m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(12, QtGui.QApplication.translate("Dialog", "3280m - 3870m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(13, QtGui.QApplication.translate("Dialog", "3870m - 4510m", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(14, QtGui.QApplication.translate("Dialog", "4510m - 5200m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "sensitivity: ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(0, QtGui.QApplication.translate("Dialog", "all parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(1, QtGui.QApplication.translate("Dialog", "Lambda: remineralization rate DOP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(2, QtGui.QApplication.translate("Dialog", "Alpha: max production rate", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(3, QtGui.QApplication.translate("Dialog", "Sigma: fraction of DOP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(4, QtGui.QApplication.translate("Dialog", "K_N: half saturation N", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(5, QtGui.QApplication.translate("Dialog", "K_I: half saturation light", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(6, QtGui.QApplication.translate("Dialog", "K_{H_2O}: attenuation water", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(7, QtGui.QApplication.translate("Dialog", "b: sinking exponent", None, QtGui.QApplication.UnicodeUTF8))

