CACHE_DIRNAME = 'accuracy'
INFORMATION_MATRIX_FILENAME = 'information_matrix.txt'
COVARIANCE_MATRIX_FILENAME = 'covariance_matrix.txt'
PARAMETER_CONFIDENCE_FILENAME = 'parameter_confidence_{alpha}_-_relative_{relative}.txt'
MODEL_CONFIDENCE_FILENAME = 'model_confidence_{alpha}_-_time_dim_confidence_{time_dim_confidence}_-_time_dim_model_{time_dim_model}.npy'
AVERAGE_MODEL_CONFIDENCE_FILENAME = 'average_model_confidence_{alpha}_-_time_dim_model_{time_dim_model}_-_relative_{relative}.txt'
AVERAGE_MODEL_CONFIDENCE_INCREASE_FILENAME = 'average_model_confidence_increase_{alpha}_-_number_of_measurements_{number_of_measurements}_-_time_dim_confidence_increase_{time_dim_confidence_increase}_-_time_dim_model_{time_dim_model}_-_relative_{relative}.npy'
