CACHE_DIRNAME = 'accuracy'
INFORMATION_MATRIX_FILENAME = 'information_matrix_-_type_{matrix_type}.txt'
CORRELATION_MATRIX_FILENAME = 'correlation_matrix_-_type_{matrix_type}.txt'
COVARIANCE_MATRIX_FILENAME = 'covariance_matrix_-_type_{matrix_type}_-_include_variance_factor_{include_variance_factor}.txt'
PARAMETER_CONFIDENCE_FILENAME = 'parameter_confidence_-_type_{matrix_type}_-_include_variance_factor_{include_variance_factor}_-_alpha_{alpha}_-_relative_{relative}.txt'
MODEL_CONFIDENCE_FILENAME = 'model_confidence_-_type_{matrix_type}_-_include_variance_factor_{include_variance_factor}_-_alpha_{alpha}_-_time_dim_confidence_{time_dim_confidence}_-_time_dim_model_{time_dim_model}.npy'
AVERAGE_MODEL_CONFIDENCE_FILENAME = 'average_model_confidence_-_type_{matrix_type}_-_include_variance_factor_{include_variance_factor}_-_alpha_{alpha}_-_time_dim_model_{time_dim_model}_-_per_tracer_{per_tracer}_-_relative_{relative}.txt'
CONFIDENCE_INCREASE_FILENAME = 'confidence_increase_-_{confidence_type}_-_include_variance_factor_{include_variance_factor}_-_alpha_{alpha}_-_number_of_measurements_{number_of_measurements}_-_time_dim_model_{time_dim_model}_-_relative_{relative}.npy'
